### ISSUE TITLE
Please consider also  tabulator and UI ontology & form system

### ISSUE THREAD

**Issue by timbl** [rdfruit/general#2]
Papers:

Tabulator:
https://pdfs.semanticscholar.org/fc88/f4d34e2a7e43fe8ffdb22dfcc2193a912c23.pdf?_ga=2.159102202.1111079707.1518835681-2059549870.1518835681

Tabulator redux:

http://events.linkeddata.org/ldow2008/papers/11-berners-lee-hollenbach-tabulator-redux.pdf

Code:

https://github.com/linkeddata/mashlib
https://github.com/linkeddata/solid-app-set
https://github.com/linkeddata/solid-ui

e.g.
https://github.com/linkeddata/solid-ui/blob/master/src/widgets/index.js#L911

Ontology:

UI  http://www.w3.org/ns/ui#

Thanks!
timbl

**Comment by l00mi** [comment]
Thank you!

Merged with README.md
